### ISSUE TITLE
[mac] VLC player window opens behind the browser window

### ISSUE THREAD

**Issue by marian-c** [stefansundin/vlc-protocol#1]
Fist of all, thanks for this! 

I've been using the mac version of this and works as expected with this small exception.

Could this be related to the `opener` app?

**Comment by stefansundin** [comment]
Hello, thanks for using it.

I have also noticed that VLC usually opens behind other windows.

It might be because of this: http://stackoverflow.com/questions/4928393/launch-an-nstask-and-bring-it-to-front#4928659

**Comment by stefansundin** [comment]
Okay, I tested NSWorkspace and it seems to do the job. Give it a try.

https://github.com/stefansundin/vlc-protocol/commit/5d2e8e17d762885ae7768862cf18307228a0c7ac

**Comment by marian-c** [comment]
Many thanks :)
