### ISSUE TITLE
Can not open VLC

### ISSUE THREAD

**Issue by L1cardo** [stefansundin/vlc-protocol#15]
I tried both Easy bat-only install and Harder exe install, after I click open, it won't do anything.
![image](https://user-images.githubusercontent.com/33802186/232802039-98d9d28e-506b-4784-bd9e-6759e46190cc.png)
![image](https://user-images.githubusercontent.com/33802186/232802106-aed83600-3937-40d5-99de-3c410898df70.png)

OS: Win11
VLC: 3.0.18
Browser: Edge

**Comment by L1cardo** [comment]
Ok, my bad, need to copy both `vlc-protocol-register.bat` and `vlc-protocol.bat` file.

**Comment by stefansundin** [comment]
Glad you got it working 👍
