### ISSUE TITLE
Instructions on building on this on OSX

### ISSUE THREAD

**Issue by mridang** [stefansundin/vlc-protocol#2]
Hi Stefan, I am unable to build this on a OSX as I get the error:

```
+ mkdir -p VLC-protocol-app/Contents/MacOS
+ gcc -framework Cocoa -o VLC-protocol-app/Contents/MacOS/vlc-protocol vlc-protocol.m
vlc-protocol.m:50:31: error: use of undeclared identifier 'NSWindowStyleMaskTitled'
                    styleMask:NSWindowStyleMaskTitled
                              ^
1 error generated.
```

Could you attached prebuild binaries to the releases page or provide instructions on how to build this? It would be very helpful. Thank you

**Comment by stefansundin** [comment]
Hi mridang.

Sure, I just released a zip here that you can use: https://github.com/stefansundin/vlc-protocol/releases/tag/v1.0.0

I'm just curious if you could help me determine why you can't compile it.
- What version of OSX are you running?
- Do you have Xcode installed? (I am guessing this is it)
- What is the output of `gcc --version`? My output is below:

```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Thanks!

**Comment by mridang** [comment]
I'm running Yosemite 10.10.5. Here's the `gcc` output:

```Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix```

I think I have the Xcode tools installed ( not sure if the headers are bundled with this). Running ` xcode-select -p` gives this:

```
/Library/Developer/CommandLineTools
```

**Comment by stefansundin** [comment]
Okay. Well, I'm not sure what is missing, but I hope the binaries worked for you at least. :)
