### ISSUE TITLE
...

### ISSUE THREAD

**Issue by makedir** [stefansundin/vlc-protocol#3]
You should leave your email or something if you are a developer, it is really annoying if you use some piece of software, and devs don't leave anything on their site to get in contact with them. Anyway, I am testing your twitch.tv VLC plugin, how do I access the stream quality via command line? "vlc.exe https://twitch.tv/channel best" doesn't work. If this is missing, please implement it.

**Comment by stefansundin** [comment]
If I understand you correctly, you are talking about [this addon](https://addons.videolan.org/p/1167220/), which does not have anything to do with this repository? There is [a gist for it](https://gist.github.com/stefansundin/c200324149bb00001fef5a252a120fc2).

In any case, I do not know how to implement what you are looking for. I have not seen any other playlist parser that allow you specify the quality from the command line. I suggest that you edit the source code (it's not very complicated), then change it so it does what you want it to do. Then if you would like to contribute your changes back, that would be appreciated.

**Comment by makedir** [comment]
Of course this has nothing to do with it... but like I said, you didn't put
any contact information on the site... so I had to post on here. It needs
to be implemented though, otherwise it's useless. I want to us it as a
replacement for livestreamer/streamlink and I need a %1 in the path for
telling what type of stream to start with, source, best, ect. I can't use
source as the first default always.

**Comment by makedir** [comment]
Please look into this, it should be possible. There is some command like:

--playlist-enqueue "blah" but that doesn't do anything with your current
Plugin. Something like this should work, no?

vlc "https://twitch.tv/quin69" --playlist-enqueue "Twitch Live - quin69 -
High (1280x720)"

but your plugin overwrites the playlist the moment it loads I guess, so you
should give options to parse it. For something like:

vlc "https://twitch.tv/quin69" --playlist-enqueue "high"
=> your plugin plays the high stream.

**Comment by makedir** [comment]
Bump.
